# Домашнее задание 7

### Свойства сложения и умножения матриц

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [3]:
B = np.array([[1, 1, 2],
              [1, 2, 1],
              [3, 2, 1]])

In [4]:
C = np.array([[0, 1, 2],
              [1, 0, 1],
              [3, 2, 0]])

In [5]:
k = 2
l = 3

### (k*l)*A = k*(l*A)

In [6]:
(k*l)*A == k*(l*A)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### k*(A + B) = k*A + kB

In [7]:
k*(A + B) == k*A + k*B

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### (k + l)*A = kA + lA

In [8]:
(k + l)*A == k*A + l*A

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### (AB)C = A(BC)

In [9]:
(A*B)*C == A*(B*C)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### (A + B)C = AC + BC

In [10]:
 (A + B)*C == A*C + B*C

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### A(B + C) = AB + AC

In [11]:
A*(B + C) == A*B + A*C

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Задание 5.1.
### Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.

In [12]:
A = np.array([[1, 2, 3, 4]])
B = np.array([[1, 2, 1, 2]])

In [13]:
# Сложение

C = A + B
C

array([[2, 4, 4, 6]])

In [14]:
# Умножение на число

C = A * 2
C

array([[2, 4, 6, 8]])

In [15]:
# Транспонирование

C = B.T
C

array([[1],
       [2],
       [1],
       [2]])

In [16]:
# Умножение через оператор

D = A*C
D

array([[1, 2, 3, 4],
       [2, 4, 6, 8],
       [1, 2, 3, 4],
       [2, 4, 6, 8]])

In [17]:
# Умножение через оператор

D = C*A
D

array([[1, 2, 3, 4],
       [2, 4, 6, 8],
       [1, 2, 3, 4],
       [2, 4, 6, 8]])

In [18]:
# Умножение через функцию

D = np.dot(A,C)
D

array([[16]])

In [19]:
# Умножение через функцию

D = np.dot(C,A)
D

array([[1, 2, 3, 4],
       [2, 4, 6, 8],
       [1, 2, 3, 4],
       [2, 4, 6, 8]])

In [20]:
# Так как порядок матриц (векторов) имеет значение при их учножении, то лучше использовать соответствующую функцию

### Задание 5.2.
### Вычислите определитель

In [21]:
A = np.array([[1, 2, 3],
              [4, 0, 6],
              [7, 8, 9]])

In [22]:
det = np.linalg.det(A)
det

59.999999999999986

### Задание 5.3.
### Вычислите матрицу, обратную данной:

In [23]:
A = np.array([[1, 2, 3],
              [4, 0, 6],
              [7, 8, 9]])

In [24]:
B = np.linalg.inv(A)
B

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

### Приведите пример матрицы 4x4, ранг которой равен 1

In [28]:
A = np.array([[1, 0, 1, 0],
              [1, 0, 1, 0],
              [1, 0, 1, 0],
              [1, 0, 1, 0]])

In [29]:
np.linalg.matrix_rank(A, 0.0001)

1

### Вычислите смешанное произведение трех векторов

In [32]:
A = np.array([1, 5, 0], float)
B = np.array([2, 8, 7], float)
C = np.array([7, 1.5, 3], float)

In [33]:
V = np.cross(A, B)

In [34]:
W = np.inner(V, C)

In [35]:
W

228.5