## Домашнее задание 6

### Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy. Полученные значения должны быть равны. Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков, а затем с использованием функций из библиотек numpy и pandas.

In [3]:
import numpy as np
import pandas as pd

In [5]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [6]:
# Ковариация вручную
cov = np.mean(zp*ks) - np.mean(zp)*np.mean(ks)
cov

9157.839999999997

In [23]:
# Ковариация через numpy
cov1 = np.cov(zp, ks, ddof=0)
cov1

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [25]:
# Коэффициент корреляции Пирсона вручную
cor = cov1/(np.std(zp, ddof=0)*np.std(ks, ddof=0))
cor

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

In [27]:
# Коэффициент корреляции через библиотеки
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

### Измерены значения IQ выборки студентов, обучающихся в местных технических вузах: 131, 125, 115, 122, 131, 115, 107, 99, 125, 111. Известно, что в генеральной совокупности IQ распределен нормально. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [14]:
iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])

In [16]:
M = np.mean(iq)
M

118.1

In [29]:
# Несмещенная СКО
S = np.std(iq, ddof=1)
S

10.54566788359614

In [31]:
M + (2.262*S/np.sqrt(10))

125.64339223691834

In [32]:
M - (2.262*S/np.sqrt(10))

110.55660776308164

### Известно, что рост футболистов в сборной распределен нормально с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27, среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [33]:
174.2 + 1.96*5/(27**0.5)

176.08601087935276

In [34]:
174.2 - 1.96*5/(27**0.5)

172.31398912064722